= Admin Persistence
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

image:https://maven-badges.herokuapp.com/maven-central/com.github.adminfaces/admin-persistence/badge.svg["Maven Central",link="http://search.maven.org/#search|ga|1|admin-persistence"]
image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/adminfaces?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

CRUD operations like a breeze for https://github.com/adminfaces[AdminFaces applications^] based on Apache DeltaSpike Data module.

== Features

TODO

== Usage

=== Classpath

First include it in your classpath:


----
<dependency>
    <groupId>com.github.adminfaces</groupId>
    <artifactId>admin-persistence</artifactId>
    <version>version</version>
</dependency>
----

[IMPORTANT]
======
Admin persistence will bring the following transitive dependencies:

----
<dependency>
    <groupId>org.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>6.1</version>
</dependency>

<dependency>
    <groupId>org.omnifaces</groupId>
    <artifactId>omnifaces</artifactId>
    <version>2.1</version>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-impl</artifactId>
    <version>version</version>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-api</artifactId>
    <version>version</version>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-data-module-api</artifactId>
    <version>version</version>
    <scope>compile</scope>
</dependency>

<dependency>
    <groupId>org.apache.deltaspike.modules</groupId>
    <artifactId>deltaspike-data-module-impl</artifactId>
    <version>version</version>
    <scope>compile</scope>
</dependency>
----    

Of cource you can override them in your pom.xml as needed.
======

=== JPA Metamodel 

As Admin Persistence uses https://deltaspike.apache.org/documentation/data.html#_jpa_criteria_api_support[DeltaSpike `typesafe criteria^] you'll need to generate JPA metamodel. There are various ways to do that, here is a maven plugin example:


[source,xml]
----
<plugin>
    <groupId>com.mysema.maven</groupId>
    <artifactId>apt-maven-plugin</artifactId>
    <version>1.1.3</version>
    <executions>
        <execution>
            <id>metamodel</id>
            <goals>
                <goal>process</goal>
            </goals>
            <configuration>
                <outputDirectory>target/generated-sources/metamodel</outputDirectory>
                <processor>org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor</processor>
            </configuration>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
            <version>4.3.8.Final</version>
        </dependency>
    </dependencies>
</plugin>
----

TIP: See https://docs.jboss.org/hibernate/orm/5.0/topical/html/metamodelgen/MetamodelGenerator.html#_usage_within_the_ide[this tutorial^] for configuring it on your IDE.



And expose an `entity manager` via CDI producer:


[source,java]
----
@ApplicationScoped
public class EntityManagerProducer {

    @PersistenceContext
    EntityManager em;

    @Produces
    public EntityManager produce() {
        return em;
    }
}

----

Extend BaseEntity on your JPA entities:

[source,java]
----
import com.github.adminfaces.persistence.model.BaseEntity;

@Entity
@Table(name = "car")
public class Car extends BaseEntity {

public Integer getId() { <1>
        return id;
    }

}
----
<1> You only need to implement a `getId()` which returns the entity primary key.

Create a service which will hold your business logic and extend CrudService:

[source,java]
----
@Stateless
public class CarService extends CrudService<Car, Integer>  {


}
----

TIP: Full source code for CarService can be https://github.com/adminfaces/admin-starter-persistence/blob/master/src/main/java/com/github/adminfaces/starter/service/CarService.java#L24[found here^].

Extend CrudMB and provide your service for your JSF managed beans to have CRUD support out of the box:

[source,java]
----
@Named
@ViewScoped
public class CarListMB extends CrudMB<Car> implements Serializable {

    @Inject
    CarService carService;

    @Inject
    @Service
    CrudService<Car, Integer> crudService; //generic injection

    @Inject
    public void initService() {
       setCrudService(carService); <1>
    }

}
----
<1> Needed by CrudMB otherwise it will throw an exception asking for CrudService initialization.

TIP: Full source code for CarListMB can be https://github.com/adminfaces/admin-starter-persistence/blob/master/src/main/java/com/github/adminfaces/starter/bean/CarListMB.java#L24[found here^].


== Pagination

Real pagination involves lots of boilerplate code, in admin-persistence it is a mater of using a Primefaces lazy datatable and bind it to a CrudMB list:


.xhtml page
[source,html]
----
 <p:dataTable widgetVar="carsTable" var="c" value="#{carListMB.list}" rows="5"
                                 rowKey="#{c.id}" lazy="true" paginator="true"

                                 <!-- other attributes -->

----

TIP: Full source code for this xhtml page can be https://github.com/adminfaces/admin-starter-persistence/blob/master/src/main/webapp/car-list.xhtml[found here^].


== Pagination filtering

For restring pages in the lazy datatable you just need to override `configRestrictions` method in the mabaged bean service (the service we set with *setCrudService* in CarListMB:

.CarService
[source,java]
----
protected Criteria<Car, Car> configRestrictions(Filter<Car> filter) {

        Criteria<Car, Car> criteria = criteria();

        //create restrictions based on parameters map
        if (filter.hasParam("id")) {
            criteria.eq(Car_.id, filter.getIntParam("id"));
        }

        if (filter.hasParam("minPrice") && filter.hasParam("maxPrice")) {
            criteria.between(Car_.price, filter.getDoubleParam("minPrice"), filter.getDoubleParam("maxPrice"));
        } else if (filter.hasParam("minPrice")) {
            criteria.gtOrEq(Car_.price, filter.getDoubleParam("minPrice"));
        } else if (filter.hasParam("maxPrice")) {
            criteria.ltOrEq(Car_.price, filter.getDoubleParam("maxPrice"));
        }

        //create restrictions based on filter entity
        if (has(filter.getEntity())) {
            Car filterEntity = filter.getEntity();
            if (has(filterEntity.getModel())) {
                criteria.likeIgnoreCase(Car_.model, "%"+filterEntity.getModel());
            }

            if (has(filterEntity.getPrice())) {
                criteria.eq(Car_.price, filterEntity.getPrice());
            }

            if (has(filterEntity.getName())) {
                criteria.likeIgnoreCase(Car_.name, "%"+filterEntity.getName());
            }
        }
        return criteria;
    }

----

[NOTE]
====
`filter.param` is a hashmap to add arbitrary parameters and `filter.entity` for entity specific ones, see https://github.com/adminfaces/admin-starter-persistence/blob/499a5d738fff90b2d3e9934b2451b90d456575e7/src/main/webapp/car-list.xhtml#L144[search dialog^] which populates those attributes:

[source,html]
----
   <div class="ui-g-12">
                    <p:outputLabel for="model" value="#{msg['label.model']}"/>
                    </div>
                    <div class="ui-g-12">
                        <p:selectOneMenu id="model" value="#{carListMB.filter.entity.model}">
                            <f:selectItem itemLabel="Chose a model" itemValue=""/>
                            <f:selectItems value="#{models}" var="m" itemLabel="#{m}"
                                           itemValue="#{m}"/>
                        </p:selectOneMenu>
                    </div>
                    <div class="ui-g-12">
                        <p:outputLabel for="name" value="#{msg['label.name']}"/>
                    </div>
                    <div class="ui-g-12">
                        <p:inputText id="name" value="#{carListMB.filter.entity.name}"/>
                    </div>

                    <div class="ui-g-6 ui-sm-12 ui-g-nopad">
                        <div class="ui-g-12">
                            <p:outputLabel for="min" value="#{msg['label.minPrice']}"/>
                        </div>
                        <div class="ui-g-12">
                            <p:inputNumber id="min" value="#{carListMB.filter.params.minPrice}"/>
                        </div>
                    </div>

                    <div class="ui-g-6 ui-sm-12 ui-g-nopad">
                        <div class="ui-g-12">
                            <p:outputLabel for="max" value="#{msg['label.maxPrice']}"/>
                        </div>
                        <div class="ui-g-12">
                            <p:inputNumber id="max" value="#{carListMB.filter.params.maxPrice}"/>
                        </div>
                    </div>
                </div>
----

====

IMPORTANT: Any datatable update (ajax or note) will trigger the configRestrictions.

NOTE: Besides filtering the `filter` helper class also holds *pagination* and *sort* information.

== Snapshots

Snapshots are published to https://oss.sonatype.org/content/repositories/snapshots/com/github/adminfaces/[maven central^] on each commit, to use it just declare the repository below on your `pom.xml`:

[source,xml]
----
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
----